/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package subproject;

public class Library {
    public static String getMessage() {
        return "Hello from Library!";
    }
}
